image: develop-registry.4pd.io/centos6_gcc7_fesql:0.0.12
services:
  - docker:dind
variables:
  GIT_SUBMODULE_STRATEGY: recursive
stages:
  - build
  - ts_integration_test
  - deploy

build:
  stage: build
  script:
    - source /root/.bashrc && sh tools/install_fesql.sh
    - ln -sf /depends/thirdparty thirdparty
    - ln -sf /depends/thirdsrc thirdsrc
    - source /root/.bashrc && bash steps/simple_compile.sh
  artifacts:
    expire_in: 4h
    paths:
      - build/bin/rtidb
      - build/src/sdk/libsql_jsdk.so
      - build/sql_pysdk/dist/*.whl

mac_build:
  variables:
    CICD_RUNNER_TAG: "rtidb_mac"
  tags:
    - rtidb_mac
  stage: build
  script:
    - bash steps/simple_compile_mac.sh
    - mv build/bin/rtidb build/bin/rtidb_mac
  artifacts:
    expire_in: 4h
    paths:
      - build/bin/rtidb_mac
      - build/src/sdk/libsql_jsdk.dylib
      - build/sql_pysdk/dist/*.whl

tablet_one_demension:
  stage: ts_integration_test
  before_script:
    - mkdir /rambuild
    - mount -t tmpfs -o size=3G tmpfs /rambuild
  script:
    - ln -sf /depends/thirdparty thirdparty
    - ln -sf /depends/thirdsrc thirdsrc
    - rm -rf ./test-output/integrationtest/test-reports/
    - sed -i 's/log_level\ =\ debug/log_level\ =\ info/g' test-common/integrationtest/conf/test.conf
    - source /root/.bashrc && source /opt/rh/python27/enable && sh steps/integration_test_on_ramdir.sh 0 "test" "ns_client"
  artifacts:
    reports:
      junit:
        - /rambuild/rtidb/test-output/integrationtest/test-reports/*
  dependencies:
    - build
  except:
    variables:
      - $ENV_BUILD == "daily"

tablet_multi_demension:
  stage: ts_integration_test
  before_script:
    - mkdir /rambuild
    - mount -t tmpfs -o size=3G tmpfs /rambuild
  script:
    - ln -sf /depends/thirdparty thirdparty
    - ln -sf /depends/thirdsrc thirdsrc
    - rm -rf ./test-output/integrationtest/test-reports/
    - sed -i 's/log_level\ =\ debug/log_level\ =\ info/g' test-common/integrationtest/conf/test.conf
    - source /root/.bashrc && source /opt/rh/python27/enable && sh steps/integration_test_on_ramdir.sh 1 "test" "ns_client"
  artifacts:
    reports:
      junit:
        - /rambuild/rtidb/test-output/integrationtest/test-reports/*
  dependencies:
    - build
  except:
    variables:
      - $ENV_BUILD == "daily"

ns_one_demension:
  stage: ns_integration_test
  before_script:
    - mkdir /rambuild
    - mount -t tmpfs -o size=3G tmpfs /rambuild
  script:
    - ln -sf /depends/thirdparty thirdparty
    - ln -sf /depends/thirdsrc thirdsrc
    - rm -rf ./test-output/integrationtest/test-reports/
    - sed -i 's/log_level\ =\ debug/log_level\ =\ info/g' test-common/integrationtest/conf/test.conf
    - source /root/.bashrc && source /opt/rh/python27/enable && sh steps/integration_test_on_ramdir.sh 0 "ns_client" "disk"
  artifacts:
    reports:
      junit:
        - /rambuild/rtidb/test-output/integrationtest/test-reports/*
  dependencies:
    - build
  except:
    variables:
      - $ENV_BUILD == "daily"

ns_multi_demension:
  stage: ns_integration_test
  before_script:
    - mkdir /rambuild
    - mount -t tmpfs -o size=3G tmpfs /rambuild
  script:
    - ln -sf /depends/thirdparty thirdparty
    - ln -sf /depends/thirdsrc thirdsrc
    - rm -rf ./test-output/integrationtest/test-reports/
    - sed -i 's/log_level\ =\ debug/log_level\ =\ info/g' test-common/integrationtest/conf/test.conf
    - source /root/.bashrc && source /opt/rh/python27/enable && sh steps/integration_test_on_ramdir.sh 1 "ns_client" "disk"
  artifacts:
    reports:
      junit:
        - /rambuild/rtidb/test-output/integrationtest/test-reports/*
  dependencies:
    - build
  except:
    variables:
      - $ENV_BUILD == "daily"
    
disk_table:
  stage: ns_integration_test
  before_script:
    - mkdir /rambuild
    - mount -t tmpfs -o size=3G tmpfs /rambuild
  script:
    - ln -sf /depends/thirdparty thirdparty
    - ln -sf /depends/thirdsrc thirdsrc
    - rm -rf ./test-output/integrationtest/test-reports/
    - sed -i 's/log_level\ =\ debug/log_level\ =\ info/g' test-common/integrationtest/conf/test.conf
    - source /root/.bashrc && source /opt/rh/python27/enable && sh steps/integration_test_on_ramdir.sh 0 "disk"
  artifacts:
    reports:
      junit:
        - /rambuild/rtidb/test-output/integrationtest/test-reports/*
  dependencies:
    - build
  except:
    variables:
      - $ENV_BUILD == "daily"

deploy-fedb:
  stage: daily
  script:
    - ln -sf /depends/thirdparty thirdparty
    - ln -sf /depends/thirdsrc thirdsrc
    - source /root/.bashrc && bash steps/deploy_package_fedb.sh
  only:
    variables:
      - $ENV_BUILD == "daily"

deploy-package:
  stage: deploy
  script:
    - ln -sf /depends/thirdparty thirdparty
    - ln -sf /depends/thirdsrc thirdsrc
    - source /root/.bashrc && bash steps/deploy_package.sh
  only:
    - tags
  except:
    variables:
      - $ENV_BUILD == "daily"
  dependencies: []

docker-image:
  stage: deploy
  script:
    - source /root/.bashrc && sh tools/install_fesql.sh
    - ln -sf /depends/thirdparty thirdparty
    - ln -sf /depends/thirdsrc thirdsrc
    - sh steps/simple_compile.sh
    - sh docker/copy_file.sh
    - make blob_proxy
    - bash docker/push_meta.sh
  only:
    - tags
    - develop
    - release/*
    - feat/push-nexus-meta
  except:
    variables:
      - $ENV_BUILD == "daily"
  dependencies: []
