image: develop-registry.4pd.io/centos6_gcc7_build_env:0.4.0
variables:
    GIT_SUBMODULE_STRATEGY: normal
    CICD_RUNNER_THIRDPARTY_PATH: "/depends/thirdparty"

before_script:
    - source tools/init_env.profile.sh

stages:
    - build
    - test
    - benchmark

style_check:
    stage: build
    script:
        - bash tools/style_check.sh
    artifacts:
        reports:
            junit:
                - ./style.xml

build_fesql_and_case:
    stage: build
    script:
        - bash tools/compile.sh
        - cd build && make coverage
    artifacts:
        reports:
            junit:
                - build/*.xml
        paths: 
            - "build/coverage"

build_fesql_and_case_on_mac:
    stage: build
    variables:
        CICD_RUNNER_THIRDPARTY_PATH: "/opt/depends/thirdparty"
        CICD_RUNNER_TAG: "macos"
    script:
        - bash tools/compile_and_test.sh
    tags:
        - macos

test_java_sdk:
    stage: test
    script:
        - bash tools/test_java_sdk.sh
    artifacts:
        reports:
            junit:
                - java/fesql-spark/target/surefire-reports/*.xml
                - java/fesql-jdbc/target/surefire-reports/*.xml

test_java_sdk_on_mac:
    stage: test
    variables:
        CICD_RUNNER_THIRDPARTY_PATH: "/opt/depends/thirdparty"
        CICD_RUNNER_TAG: "macos"
    script:
        - bash tools/test_java_sdk.sh
    after_script:
        - cd onebox && sh stop_all.sh
    tags:
        - macos
    artifacts:
        reports:
            junit:
                - java/fesql-spark/target/surefire-reports/*.xml
                - java/fesql-jdbc/target/surefire-reports/*.xml
test_py3sdk_linux:
    stage: test
    script:
        - bash tools/run_py3_ut.sh
    artifacts:
        reports:
            junit:
                - python/test/*.xml

                  #test_py3sdk_mac:
                  #    stage: test
                  #    variables:
                  #        CICD_RUNNER_THIRDPARTY_PATH: "/opt/depends/thirdparty"
                  #        CICD_RUNNER_TAG: "macos"
                  #    tags:
                  #        - macos
                  #    script:
                  #        - bash tools/run_py3_ut.sh
                  #    after_script:
                  #        - cd onebox && sh stop_all.sh
                  #    artifacts:
                  #        reports:
                  #            junit:
                  #                - python/test/*.xml
                  #
micro_benchmark:
    stage: benchmark
    script:
        - bash tools/micro_bench.sh
