image: develop-registry.4pd.io/centos6_gcc7_rtidb_build:0.0.4
stages:
    - build
    - it-ns

build_rtidb_and_case:
    stage: build
    script:
        - ln -sf /usr/workdir/thirdparty thirdparty
        - ln -sf /usr/workdir/thirdsrc thirdsrc
        - source /root/.bashrc && bash steps/compile.sh
    artifacts:
        expire_in: 1h
        paths:
            - build/

ns_one_demension:
    stage: it-ns
    script:
        - ln -sf /usr/workdir/thirdparty thirdparty
        - ln -sf /usr/workdir/thirdsrc thirdsrc
        - rm -rf ./test-output/integrationtest/test-reports/
        - sed -i 's/log_level\ =\ debug/log_level\ =\ info/g' test-common/integrationtest/conf/test.conf
        - source /root/.bashrc && LD_LIBRARY_PATH=/usr/workdir/thirdparty/lib:$LD_LIBRARY_PATH
        - bash steps/integration_test.sh 0 "ns_client"
    artifacts:
        reports:
            junit:
                - ./test-output/integrationtest/test-reports/*.xml

ns_multi_demension:
    stage: it-ns
    script:
        - ln -sf /usr/workdir/thirdparty thirdparty
        - ln -sf /usr/workdir/thirdsrc thirdsrc
        - rm -rf ./test-output/integrationtest/test-reports/
        - sed -i 's/log_level\ =\ debug/log_level\ =\ info/g' test-common/integrationtest/conf/test.conf
        - source /root/.bashrc && LD_LIBRARY_PATH=/usr/workdir/thirdparty/lib:$LD_LIBRARY_PATH
        - bash steps/integration_test.sh 1 "ns_client"
    artifacts:
        reports:
            junit:
                - ./test-output/integrationtest/test-reports/*.xml