image: develop-registry.4pd.io/centos6_gcc7_build_env:0.5.1
services:
    - docker:dind
variables:
    GIT_SUBMODULE_STRATEGY: recursive
stages:
    - make_docker


docker-image:
    stage: make_docker
    script:
        - source /root/.bashrc && sh tools/install_fesql.sh
        - ln -sf /depends/thirdparty thirdparty
        - ln -sf /depends/thirdsrc thirdsrc
        - sh steps/simple_compile.sh
        - sh docker/copy_file.sh
        - make blob_proxy
        - bash docker/push_meta.sh
    only:
        - tags
        - develop
        - feat/push-nexus-meta
        - release/*
