# Copyright 2021 4Paradigm
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

image: develop-registry.4pd.io/centos6_gcc7_fesql:0.0.13
variables:
    GIT_SUBMODULE_STRATEGY: normal
    CICD_RUNNER_THIRDPARTY_PATH: "/depends/thirdparty"

before_script:
    - source tools/init_env.profile.sh

stages:
    - style
    - build
    - test
    - deploy

style_check:
    stage: style
    script:
        - bash tools/style_check.sh
    artifacts:
        reports:
            junit:
                - ./style.xml


build_hybridse_on_linux:
    stage: build
    script:
        - bash tools/hybridse_build.sh
        - bash tools/cicd/gen_intermediate_cicd_artifacts.sh linux
        - bash tools/documentation/export_udf_doc.sh
    artifacts:
        paths:
            - intermediate_cicd_artifact_linux.tar.gz
            - hybridse-*.tar.gz

coverage_report:
    stage: build
    script:
        - bash tools/compile_and_coverage.sh
    artifacts:
        reports:
            junit:
                - build/*.xml
        paths:
            - build/coverage

test_hybridse_core_on_linux:
    stage: test
    script:
        - bash tools/hybridse_core_test.sh

test_hybridse_examples_on_linux:
    stage: test
    script:
        - bash tools/hybridse_examples_test.sh

test_hybridse_java_on_linux:
    stage: test
    script:
        - bash tools/cicd/extract_intermediate_cicd_artifacts.sh linux
        - bash tools/test_java_sdk.sh
    dependencies:
        - build_hybridse_on_linux
    artifacts:
        reports:
            junit:
                - java/hybridse-common/target/surefire-reports/*.xml

micro_benchmark:
    stage: deploy
    script:
        - bash tools/micro_bench.sh | tee micro_bench_report.txt
        - bash tools/gen_micro_bench_compare.sh
    dependencies:
        - build_hybridse_on_linux
    artifacts:
        paths:
            - ./micro_bench_report.txt
            - ./benchmark_compare.html
            
#deploy_jar:
#    stage: deploy
#    script:
#        - bash tools/cicd/extract_intermediate_cicd_artifacts.sh linux
#        - bash tools/cicd/deploy_hybridse_java_jar.sh
#    dependencies:
#        - build_hybridse_on_linux
#    artifacts:
#        paths:
#            - ./java/hybridse-spark/target/*.jar



