image: develop-registry.4pd.io/centos6_gcc7_rtidb_build:0.0.9
stages:
    - build
    - ut
    - it-tablet
    - it-ns
    - deploy

build_rtidb:
    stage: build
    script:
        - ln -sf /usr/workdir/thirdparty thirdparty
        - ln -sf /usr/workdir/thirdsrc thirdsrc
        - source /root/.bashrc && bash steps/compile.sh
    artifacts:
        expire_in: 2h
        paths:
            - build/bin/rtidb
    except:
        - /^*pz-fpga*$/

style_check:
    stage: build
    script:
        - source /root/.bashrc && bash tools/style_check.sh
    artifacts:
        reports:
            junit:
                - reports/*.xml

cpp_ut:
    stage: ut
    script:
        - ln -sf /usr/workdir/thirdparty thirdparty
        - ln -sf /usr/workdir/thirdsrc thirdsrc
        - source /root/.bashrc && bash steps/compile.sh
        - source /root/.bashrc && LD_LIBRARY_PATH=/usr/workdir/thirdparty/lib:$LD_LIBRARY_PATH bash steps/ut.sh
    artifacts:
        reports:
            junit:
                - reports/*.xml
    except:
        - /^*pz-fpga*$/
java_ut:
    stage: ut
    script:
        - ln -sf /usr/workdir/thirdparty thirdparty
        - ln -sf /usr/workdir/thirdsrc thirdsrc
        - source /root/.bashrc && LD_LIBRARY_PATH=/usr/workdir/thirdparty/lib:$LD_LIBRARY_PATH bash steps/java_ut.sh
    artifacts:
        reports:
            junit:
                - java/target/surefire-reports/junitreports/TEST-*.xml
                - java/target/surefire-reports/TEST-*.xml
                - java/target/failsafe-reports/junitreports/TEST-*.xml
                - java/target/failsafe-reports/TEST-*.xml
    except:
        - /^*pz-fpga*$/

tablet_one_demension:
    stage: it-tablet
    script:
        - ln -sf /usr/workdir/thirdparty thirdparty
        - ln -sf /usr/workdir/thirdsrc thirdsrc
        - rm -rf ./test-output/integrationtest/test-reports/
        - sed -i 's/log_level\ =\ debug/log_level\ =\ info/g' test-common/integrationtest/conf/test.conf
        - source /root/.bashrc && LD_LIBRARY_PATH=/usr/workdir/thirdparty/lib:$LD_LIBRARY_PATH
        - sh steps/integration_test.sh 0 "test" "ns_client"
    artifacts:
        reports:
            junit:
                - ./test-output/integrationtest/test-reports/*.xml
    except:
        - /^*pz-fpga*$/

tablet_multi_demension:
    stage: it-tablet
    script:
        - ln -sf /usr/workdir/thirdparty thirdparty
        - ln -sf /usr/workdir/thirdsrc thirdsrc
        - rm -rf ./test-output/integrationtest/test-reports/
        - sed -i 's/log_level\ =\ debug/log_level\ =\ info/g' test-common/integrationtest/conf/test.conf
        - source /root/.bashrc && LD_LIBRARY_PATH=/usr/workdir/thirdparty/lib:$LD_LIBRARY_PATH
        - sh steps/integration_test.sh 1 "test" "ns_client"
    artifacts:
        reports:
            junit:
                - ./test-output/integrationtest/test-reports/*.xml
    except:
        - /^*pz-fpga*$/

ns_one_demension:
    stage: it-ns
    script:
        - ln -sf /usr/workdir/thirdparty thirdparty
        - ln -sf /usr/workdir/thirdsrc thirdsrc
        - rm -rf ./test-output/integrationtest/test-reports/
        - sed -i 's/log_level\ =\ debug/log_level\ =\ info/g' test-common/integrationtest/conf/test.conf
        - source /root/.bashrc && LD_LIBRARY_PATH=/usr/workdir/thirdparty/lib:$LD_LIBRARY_PATH
        - bash steps/integration_test.sh 0 "ns_client" "disk"
    artifacts:
        reports:
            junit:
                - ./test-output/integrationtest/test-reports/*.xml
    except:
        - /^*pz-fpga*$/

ns_multi_demension:
    stage: it-ns
    script:
        - ln -sf /usr/workdir/thirdparty thirdparty
        - ln -sf /usr/workdir/thirdsrc thirdsrc
        - rm -rf ./test-output/integrationtest/test-reports/
        - sed -i 's/log_level\ =\ debug/log_level\ =\ info/g' test-common/integrationtest/conf/test.conf
        - source /root/.bashrc && LD_LIBRARY_PATH=/usr/workdir/thirdparty/lib:$LD_LIBRARY_PATH
        - bash steps/integration_test.sh 1 "ns_client" "disk"
    artifacts:
        reports:
            junit:
                - ./test-output/integrationtest/test-reports/*.xml
    except:
        - /^*pz-fpga*$/

disk_table:
    stage: it-ns
    script:
        - ln -sf /usr/workdir/thirdparty thirdparty
        - ln -sf /usr/workdir/thirdsrc thirdsrc
        - rm -rf ./test-output/integrationtest/test-reports/
        - sed -i 's/log_level\ =\ debug/log_level\ =\ info/g' test-common/integrationtest/conf/test.conf
        - source /root/.bashrc && LD_LIBRARY_PATH=/usr/workdir/thirdparty/lib:$LD_LIBRARY_PATH
        - bash steps/integration_test.sh 0 "disk"
    artifacts:
        reports:
            junit:
                - ./test-output/integrationtest/test-reports/*.xml
    except:
        - /^*pz-fpga*$/

disktable-java:
    stage: ut
    script:
        - ln -sf /usr/workdir/thirdparty thirdparty
        - ln -sf /usr/workdir/thirdsrc thirdsrc
        - source /root/.bashrc && bash steps/auto_test.sh
    artifacts:
        reports:
            junit:
                - rtidb-auto-test/target/surefire-reports/junitreports/TEST-*.xml
                - rtidb-auto-test/target/surefire-reports/TEST-*.xml
                - rtidb-auto-test/target/failsafe-reports/junitreports/TEST-*.xml
                - rtidb-auto-test/target/failsafe-reports/TEST-*.xml
    except:
        - /^*pz-fpga*$/

deploy-package:
    stage: deploy
    script:
        - ln -sf /usr/workdir/thirdparty thirdparty
        - ln -sf /usr/workdir/thirdsrc thirdsrc
        - source /root/.bashrc && bash steps/deploy_package.sh
    only:
        - tags
    except:
        - /^*pz-fpga*$/
        
build_rtidb_pz:
    image: develop-registry.4pd.io/build-titans-devtoolset7-rhpython36:0.2
    stage: build
    script:
        - ln -sf /workdir/thirdparty thirdparty
        - ln -sf /workdir/thirdsrc thirdsrc
        - bash steps/get_pz_fpga_deps.sh
        - sed -i 's/\"Enable STATIC COMPILE\"\ ON/\"Enable STATIC COMPILE\"\ OFF/g' CMakeLists.txt
        - sed -i 's/\"Enable pz compression for ssd tables\"\ OFF/\"Enable pz compression for ssd tables\"\ ON/g' CMakeLists.txt
        # - echo '\n--file_compression=pz\n' >> release/conf/tablet.flags
        - source /root/.bashrc && bash steps/compile.sh
        - mkdir TitanSE-rtidb && cp release/* TitanSE-rtidb/ -rf && cp tools TitanSE-rtidb/ -rf && cp build/bin/rtidb TitanSE-rtidb/bin/
        - mkdir TitanSE-rtidb/lib && cp thirdparty/bin/*.so* TitanSE-rtidb/lib/ -L
        - tar zcf TitanSE-rtidb-${CI_COMMIT_SHA:0:8}.tar.gz TitanSE-rtidb
        - curl -T TitanSE-rtidb-${CI_COMMIT_SHA:0:8}.tar.gz ftp://172.27.12.154/pub/team_hpc/pz_rtidb/
    artifacts:
        expire_in: 2h
        paths:
            - build/bin/rtidb
    only:
        - /^*pz-fpga*$/
