image: develop-registry.4pd.io/centos6_gcc7_fesql:0.0.8
variables:
    GIT_SUBMODULE_STRATEGY: normal

stages:
    - build
    - benchmark

style_check:
    stage: build
    script:
        - source /opt/rh/python27/enable && bash tools/style_check.sh
    artifacts:
        reports:
            junit:
                - ./style.xml

build_py3sdk_and_case:
    stage: build
    script:
        - ln -sf /depends/thirdparty thirdparty
        - source /opt/rh/devtoolset-7/enable && bash tools/run_py3_ut.sh
    artifacts:
        reports:
            junit:
                - python/test/*.xml

build_fesql_and_case:
    stage: build
    script:
        - ln -sf /depends/thirdparty thirdparty
        - source /opt/rh/devtoolset-7/enable && bash tools/compile.sh
        - cd build && make coverage
    artifacts:
        reports:
            junit:
                - build/*.xml
        paths: ["build/coverage"]

micro_benchmark:
    stage: benchmark
    script:
        - ln -sf /depends/thirdparty thirdparty
        - source /opt/rh/devtoolset-7/enable && bash tools/micro_bench.sh

