image: develop-registry.4pd.io/centos6_gcc7_rtidb_build:0.0.4
stages:
    - build
    - ut

build_rtidb_and_case:
    stage: build
    script: 
        - ln -sf /usr/workdir/thirdparty thirdparty
        - ln -sf /usr/workdir/thirdsrc thirdsrc
        - source /root/.bashrc && bash steps/compile.sh
    artifacts:
        expire_in: 1h
        paths:
            - build/
cpp_ut:
    stage: ut
    script:
        - ln -sf /usr/workdir/thirdparty thirdparty
        - ln -sf /usr/workdir/thirdsrc thirdsrc
        - source /root/.bashrc && LD_LIBRARY_PATH=/usr/workdir/thirdparty/lib:$LD_LIBRARY_PATH bash steps/ut.sh
    artifacts:
        reports:
            junit:
                - reports/*.xml
java_ut:
    stage: ut
    script:
        - ln -sf /usr/workdir/thirdparty thirdparty
        - ln -sf /usr/workdir/thirdsrc thirdsrc
        - source /root/.bashrc && LD_LIBRARY_PATH=/usr/workdir/thirdparty/lib:$LD_LIBRARY_PATH bash steps/java_ut.sh
    artifacts:
        reports:
            junit:
                - java/target/surefire-reports/junitreports/TEST-*.xml
                - java/target/surefire-reports/TEST-*.xml
                - java/target/failsafe-reports/junitreports/TEST-*.xml
                - java/target/failsafe-reports/TEST-*.xml
            
it_one_demension:
    stage: ut
    script:
        - ln -sf /usr/workdir/thirdparty thirdparty
        - ln -sf /usr/workdir/thirdsrc thirdsrc
        - sed -i 's/log_level\ =\ debug/log_level\ =\ info/g' test-common/integrationtest/conf/test.conf
        - source /root/.bashrc && LD_LIBRARY_PATH=/usr/workdir/thirdparty/lib:$LD_LIBRARY_PATH bash steps/integration_test.sh 0 "ns_client"
        - rm -rf ./test-output/integrationtest/test-reports/one-demension 
        - mkdir -p ./one-demension
        - mv ./test-output/integrationtest/test-reports/*.xml ./one-demension
    artifacts:
        reports:
            junit:
                - one-demension/*.xml

it_multi_demension:
    stage: ut
    script:
        - ln -sf /usr/workdir/thirdparty thirdparty
        - ln -sf /usr/workdir/thirdsrc thirdsrc
        - sed -i 's/log_level\ =\ debug/log_level\ =\ info/g' test-common/integrationtest/conf/test.conf
        - source /root/.bashrc && LD_LIBRARY_PATH=/usr/workdir/thirdparty/lib:$LD_LIBRARY_PATH bash steps/integration_test.sh 1 "ns_client"
        - mkdir -p ./multi-demension
        - mv ./test-output/integrationtest/test-reports/*.xml ./multi-demension
    artifacts:
        reports:
            junit:
                - multi-demension/*.xml
