image: develop-registry.4pd.io/fesql_build_base:0.2
variables:
    GIT_SUBMODULE_STRATEGY: normal
stages:
    - build
build_fesql_and_case:
    stage: build
    script:
        - ln -sf /depends/thirdparty thirdparty
        - source /opt/rh/devtoolset-8/enable && bash tools/compile.sh
        - cd build && src/base/flat_mk
    artifacts:
        reports:
            junit:
                - build/*.xml



