image: develop-registry.4pd.io/centos6_gcc7_fesql:0.0.12
services:
  - docker:dind
variables:
  GIT_SUBMODULE_STRATEGY: recursive
stages:
  - precheck
  - build
    #- daily
    # - quick
  - manual
  - deploy

style_check:
  stage: precheck
  except:
    variables:
      - $ENV_BUILD == "daily"
  script:
    - source /root/.bashrc && bash tools/style_check.sh
  artifacts:
    reports:
      junit:
        - ./reports/style.xml


build:
  stage: build
  script:
    - source /root/.bashrc && sh tools/install_fesql.sh
    - ln -sf /depends/thirdparty thirdparty
    - ln -sf /depends/thirdsrc thirdsrc
    - source /root/.bashrc && bash steps/simple_compile.sh
  artifacts:
    expire_in: 4h
    paths:
      - build/bin/rtidb
      - build/src/sdk/libsql_jsdk.so
      - build/sql_pysdk/dist/*.whl
      - build/python/dist/*.whl

# mac_build:
#   variables:
#     CICD_RUNNER_TAG: "rtidb_mac"
#   tags:
#     - rtidb_mac
#   stage: build
#   script:
#     - bash steps/simple_compile_mac.sh
#     - mv build/bin/rtidb build/bin/rtidb_mac
#   artifacts:
#     expire_in: 4h
#     paths:
#       - build/bin/rtidb_mac
#       - build/src/sdk/libsql_jsdk.dylib
#       - build/sql_pysdk/dist/*.whl
#   only:
#     variables:
#       - $ENV_BUILD == "daily"

fpga_c++_ut:
  image: develop-registry.4pd.io/centos6_gcc7_fesql_fpga:0.0.12
  tags:
    - fpga
  stage: manual
  script:
    - source /root/.bashrc && sh tools/install_fesql.sh
    - ln -sf /depends/thirdparty thirdparty
    - ln -sf /depends/thirdsrc thirdsrc
    - source /root/.bashrc && bash steps/fpga_compile.sh
    - source /root/.bashrc && LD_LIBRARY_PATH=/depends/thirdparty/lib:$LD_LIBRARY_PATH bash steps/ut.sh
  artifacts:
    reports:
      junit:
        - reports/*.xml
  dependencies:
    - build
  except:
    variables:
      - $ENV_BUILD == "daily"
  when: manual

#fpga_java_ut:
#  image: develop-registry.4pd.io/centos6_gcc7_fesql_fpga:0.0.12
#  tags:
#    - fpga
#  stage: test
#  except:
#    variables:
#      - $ENV_BUILD == "daily"
#  before_script:
#    - mkdir /rambuild
#    - mount -t tmpfs -o size=3G tmpfs /rambuild
#  script:
#    - ln -sf /depends/thirdparty thirdparty
#    - ln -sf /depends/thirdsrc thirdsrc
#    - source /root/.bashrc && sh tools/install_fesql.sh
#    - source /root/.bashrc && bash steps/simple_compile_fpga.sh
#    - source /root/.bashrc && LD_LIBRARY_PATH=/depends/thirdparty/lib:$LD_LIBRARY_PATH bash steps/java_ut.sh
#  after_script:
#    - tar czvf $CI_COMMIT_SHA rtidb-auto-test-java/target/allure-results
#    - bash steps/upload-nexus.sh $CI_COMMIT_SHA
#    - curl -s "http://auto.4paradigm.com/job/rtidb-test-report/buildWithParameters?token=gitlab&allure_path=rtidb-auto-test-java/target/allure-results&pkg=$CI_COMMIT_SHA&buildname=$CI_PIPELINE_ID"-"$CI_JOB_ID"
#    - bash steps/get-report-url.sh rtidb-test-report $CI_PIPELINE_ID"-"$CI_JOB_ID
#  artifacts:
#    reports:
#      junit:
#        - java/target/surefire-reports/junitreports/TEST-*.xml
#        - java/target/surefire-reports/TEST-*.xml
#        - java/target/failsafe-reports/junitreports/TEST-*.xml
#        - java/target/failsafe-reports/TEST-*.xml


fesql_auto_test:
  stage: manual
  before_script:
    - mkdir /rambuild
    - mount -t tmpfs -o size=3G tmpfs /rambuild
  script:
    - ln -sf /depends/thirdparty thirdparty
    - ln -sf /depends/thirdsrc thirdsrc
    - source /root/.bashrc && LD_LIBRARY_PATH=/depends/thirdparty/lib:$LD_LIBRARY_PATH bash steps/fesql_auto_test.sh
    - source /root/.bashrc && LD_LIBRARY_PATH=/depends/thirdparty/lib:$LD_LIBRARY_PATH bash steps/fesql_auto_test_cluster.sh
  after_script:
    - tar czf $CI_COMMIT_SHA  src/sdk/java/fesql-auto-test-java/target/allure-results
    - bash steps/upload-nexus.sh $CI_COMMIT_SHA
    - curl -s "http://auto.4paradigm.com/job/fesql-test-report/buildWithParameters?token=gitlab&pkg=$CI_COMMIT_SHA&allure_path=src/sdk/java/feql-auto-test-java/target/allure-results&buildname=$CI_PIPELINE_ID"-"$CI_JOB_ID"
    - bash steps/get-report-url.sh rtidb-test-report $CI_PIPELINE_ID"-"$CI_JOB_ID
  artifacts:
    reports:
      junit:
        - src/sdk/java/fesql-auto-test-java/target/surefire-reports/junitreports/TEST-*.xml
        - src/sdk/java/fesql-auto-test-java/target/surefire-reports/TEST-*.xml
        - src/sdk/java/fesql-auto-test-java/target/failsafe-reports/junitreports/TEST-*.xml
        - src/sdk/java/fesql-auto-test-java/target/failsafe-reports/TEST-*.xml
  except:
    variables:
      - $ENV_BUILD == "daily"
  dependencies:
    - build
  when: manual

auto_test:
  stage: manual
  except:
    variables:
      - $ENV_BUILD == "daily"
  before_script:
    - mkdir /rambuild
    - mount -t tmpfs -o size=5G tmpfs /rambuild
  script:
    - ln -sf /depends/thirdparty thirdparty
    - ln -sf /depends/thirdsrc thirdsrc
    - source /root/.bashrc && bash steps/auto_test.sh steps/rtidb_integration_test.properties
  after_script:
    - tar czvf $CI_COMMIT_SHA rtidb-auto-test-java/target/allure-results
    - bash steps/upload-nexus.sh $CI_COMMIT_SHA
    - curl -s "http://auto.4paradigm.com/job/rtidb-test-report/buildWithParameters?token=gitlab&allure_path=rtidb-auto-test-java/target/allure-results&pkg=$CI_COMMIT_SHA&buildname=$CI_PIPELINE_ID"-"$CI_JOB_ID"
    - bash steps/get-report-url.sh rtidb-test-report $CI_PIPELINE_ID"-"$CI_JOB_ID
  artifacts:
    reports:
      junit:
        - rtidb-auto-test-java/target/surefire-reports/junitreports/TEST-*.xml
        - rtidb-auto-test-java/target/surefire-reports/TEST-*.xml
        - rtidb-auto-test-java/target/failsafe-reports/junitreports/TEST-*.xml
        - rtidb-auto-test-java/target/failsafe-reports/TEST-*.xml
  except:
    variables:
      - $ENV_BUILD == "daily"
  dependencies:
    - build
  when: manual

auto_test_add_index_column:
  stage: manual
  except:
    variables:
      - $ENV_BUILD == "daily"
  before_script:
    - mkdir /rambuild
    - mount -t tmpfs -o size=5G tmpfs /rambuild
  script:
    - ln -sf /depends/thirdparty thirdparty
    - ln -sf /depends/thirdsrc thirdsrc
    - source /root/.bashrc && bash steps/auto_test.sh steps/rtidb_integration_test_1620.properties
  after_script:
    - tar czvf $CI_COMMIT_SHA rtidb-auto-test-java/target/allure-results
    - bash steps/upload-nexus.sh $CI_COMMIT_SHA
    - curl -s "http://auto.4paradigm.com/job/rtidb-test-report/buildWithParameters?token=gitlab&allure_path=rtidb-auto-test-java/target/allure-results&pkg=$CI_COMMIT_SHA&buildname=$CI_PIPELINE_ID"-"$CI_JOB_ID"
    - bash steps/get-report-url.sh rtidb-test-report $CI_PIPELINE_ID"-"$CI_JOB_ID
  artifacts:
    reports:
      junit:
        - rtidb-auto-test-java/target/surefire-reports/junitreports/TEST-*.xml
        - rtidb-auto-test-java/target/surefire-reports/TEST-*.xml
        - rtidb-auto-test-java/target/failsafe-reports/junitreports/TEST-*.xml
        - rtidb-auto-test-java/target/failsafe-reports/TEST-*.xml
  except:
    variables:
      - $ENV_BUILD == "daily"
  dependencies:
    - build
  when: manual

c++_ut:
  stage: quick
  script:
    - source /root/.bashrc && sh tools/install_fesql.sh
    - ln -sf /depends/thirdparty thirdparty
    - ln -sf /depends/thirdsrc thirdsrc
    - source /root/.bashrc && bash steps/compile.sh
    - source /root/.bashrc && LD_LIBRARY_PATH=/depends/thirdparty/lib:$LD_LIBRARY_PATH bash steps/ut.sh
  artifacts:
    reports:
      junit:
        - reports/*.xml
  dependencies:
    - build
  except:
    variables:
      - $ENV_BUILD == "daily"

py3_ut:
  stage: quick
  before_script:
    - mkdir /rambuild
    - mount -t tmpfs -o size=3G tmpfs /rambuild
  script:
    - ln -sf /depends/thirdparty thirdparty
    - ln -sf /depends/thirdsrc thirdsrc
    - source /root/.bashrc && LD_LIBRARY_PATH=/depends/thirdparty/lib:$LD_LIBRARY_PATH bash steps/run_py3_ut.sh
  artifacts:
    reports:
      junit:
        - ./python/test/*xml
  dependencies:
    - build
  except:
    variables:
      - $ENV_BUILD == "daily"

fesql_auto_test_python:
  stage: manual
  before_script:
    - mkdir /rambuild
    - mount -t tmpfs -o size=3G tmpfs /rambuild
  script:
    - ln -sf /depends/thirdparty thirdparty
    - ln -sf /depends/thirdsrc thirdsrc
    - source /root/.bashrc && LD_LIBRARY_PATH=/depends/thirdparty/lib:$LD_LIBRARY_PATH bash steps/fesql_auto_test_python.sh
  artifacts:
    reports:
      junit:
        - src/sdk/python/fesql-auto-test-python/report/TEST-test_*.xml
  except:
    variables:
      - $ENV_BUILD == "daily"
  dependencies:
    - build
  when: manual

fesql_test_python:
  stage: manual
  before_script:
    - mkdir /rambuild
    - mount -t tmpfs -o size=3G tmpfs /rambuild
  script:
    - ln -sf /depends/thirdparty thirdparty
    - ln -sf /depends/thirdsrc thirdsrc
    - source /root/.bashrc && LD_LIBRARY_PATH=/depends/thirdparty/lib:$LD_LIBRARY_PATH bash steps/fesql_test_python.sh
  artifacts:
    reports:
      junit:
        - src/sdk/python/sqlalchemy-test/*xml
  except:
    variables:
      - $ENV_BUILD == "daily"
  dependencies:
    - build
  when: manual

tablet_one_demension:
  stage: manual
  before_script:
    - mkdir /rambuild
    - mount -t tmpfs -o size=3G tmpfs /rambuild
  script:
    - ln -sf /depends/thirdparty thirdparty
    - ln -sf /depends/thirdsrc thirdsrc
    - sed -i 's/log_level\ =\ debug/log_level\ =\ info/g' test-common/integrationtest/conf/test.conf
    - source /root/.bashrc && source /opt/rh/python27/enable && sh steps/integration_test_on_ramdir.sh 0 "test" "ns_client"
    - cp -r /rambuild/rtidb/test-output/integrationtest/test-reports ./
  artifacts:
    reports:
      junit:
        - ./test-reports/*
  dependencies:
    - build
  except:
    variables:
      - $ENV_BUILD == "daily"
  when: manual

