image: develop-registry.4pd.io/fesql_build_base:0.9
variables:
    GIT_SUBMODULE_STRATEGY: normal

stages:
    - build
    - benchmark

style_check:
    stage: build
    script:
        - bash tools/style_check.sh
    artifacts:
        reports:
            junit:
                - ./style.xml

build_fesql_and_case:
    stage: build
    script:
        - ln -sf /depends/thirdparty thirdparty
        - source /opt/rh/devtoolset-8/enable && bash tools/compile.sh
        - cd build && make coverage
    artifacts:
        reports:
            junit:
                - build/*.xml
        paths: ["build/coverage"]

micro_benchmark:
    stage: benchmark
    script:
        - ln -sf /depends/thirdparty thirdparty
        - source /opt/rh/devtoolset-8/enable && bash tools/micro_bench.sh



