image: develop-registry.4pd.io/centos6_gcc7_fesql:0.0.12
services:
  - docker:dind
variables:
  GIT_SUBMODULE_STRATEGY: recursive
stages:
  - build
  - ts_integration_test

build:
  stage: build
  script:
    - source /root/.bashrc && sh tools/install_fesql.sh
    - ln -sf /depends/thirdparty thirdparty
    - ln -sf /depends/thirdsrc thirdsrc
    - source /root/.bashrc && bash steps/simple_compile.sh
  artifacts:
    expire_in: 4h
    paths:
      - build/bin/rtidb
      - build/src/sdk/libsql_jsdk.so
      - build/sql_pysdk/dist/*.whl

tablet_one_demension:
  stage: ts_integration_test
  before_script:
    - mkdir /rambuild
    - mount -t tmpfs -o size=3G tmpfs /rambuild
  script:
    - ln -sf /depends/thirdparty thirdparty
    - ln -sf /depends/thirdsrc thirdsrc
    - rm -rf ./test-output/integrationtest/test-reports/
    - sed -i 's/log_level\ =\ debug/log_level\ =\ info/g' test-common/integrationtest/conf/test.conf
    - source /root/.bashrc && source /opt/rh/python27/enable && sh steps/integration_test_on_ramdir.sh 0 "test" "ns_client"
  artifacts:
    reports:
      junit:
        - /rambuild/rtidb/test-output/integrationtest/test-reports/*
  dependencies:
    - build
  except:
    variables:
      - $ENV_BUILD == "daily"
