image: develop-registry.4pd.io/fesql_build_base:0.3
variables:
    GIT_SUBMODULE_STRATEGY: normal
stages:
    - build
build_rtidb_and_case:
    stage: build
    script:
        - ln -sf /depends/thirdparty thirdparty
        - source /opt/rh/devtoolset-8/enable && bash tools/compile.sh
        - cd build && make coverage 
    artifacts:
        reports:
            junit:
                - build/*.xml
                - build/coverage




