image: develop-registry.4pd.io/centos6_gcc7_fesql:0.0.13
variables:
    GIT_SUBMODULE_STRATEGY: normal
    CICD_RUNNER_THIRDPARTY_PATH: "/depends/thirdparty"

before_script:
    - source tools/init_env.profile.sh

stages:
    - build
    - test
    - deploy

style_check:
    stage: build
    script:
        - bash tools/style_check.sh
    artifacts:
        reports:
            junit:
                - ./style.xml

coverage_report:
    stage: build
    script:
        - bash tools/compile_and_coverage.sh
    artifacts:
        reports:
            junit:
                - build/*.xml
        paths: 
            - build/coverage

build_fesql_on_linux:
    stage: build
    script:
        - bash tools/compile_and_test.sh
        - bash tools/cicd/gen_intermediate_java_cicd_artifacts.sh linux
        - bash tools/documentation/export_udf_doc.sh
#        - tar cfz bm_cases.tar.gz build/src/bm/*_bm
    artifacts:
        paths:
            - java_intermediate_cicd_artifact_linux.tar.gz
#            - build/python/dist/*.whl
#            - build/src/fesql
#            - bm_cases.tar.gz

build_fesql_on_mac:
    stage: build
    variables:
        CICD_RUNNER_THIRDPARTY_PATH: "/opt/depends/thirdparty"
        CICD_RUNNER_TAG: "macos"
    script:
        - bash tools/compile_and_test.sh
        - bash tools/cicd/gen_intermediate_java_cicd_artifacts.sh mac
    tags:
        - macos
    artifacts:
        paths:
            - java_intermediate_cicd_artifact_mac.tar.gz
            - build/src/fesql

test_java_sdk_on_linux:
    stage: test
    script:
        - bash tools/cicd/extract_intermediate_java_cicd_artifacts.sh linux
        - bash tools/test_java_sdk.sh
    dependencies:
        - build_fesql_on_linux
    artifacts:
        reports:
            junit:
                - java/fesql-spark/target/surefire-reports/*.xml
                - java/fesql-jdbc/target/surefire-reports/*.xml

# test_java_sdk_on_mac:
#    stage: test
#    variables:
#        CICD_RUNNER_THIRDPARTY_PATH: "/opt/depends/thirdparty"
#        CICD_RUNNER_TAG: "macos"
#    script:
#        - bash tools/cicd/extract_intermediate_java_cicd_artifacts.sh mac
#        - bash tools/test_java_sdk.sh
#    after_script:
#        - cd onebox && sh stop_all.sh
#    tags:
#        - macos
#    dependencies:
#        - build_fesql_on_mac
#    artifacts:
#        reports:
#            junit:
#                - java/fesql-spark/target/surefire-reports/*.xml
#                - java/fesql-jdbc/target/surefire-reports/*.xml

test_py3sdk_linux:
    stage: test
    script:
        - bash tools/run_py3_ut.sh
    dependencies:
        - build_fesql_on_linux
    artifacts:
        reports:
            junit:
                - python/test/*.xml

                  #test_py3sdk_mac:
                  #    stage: test
                  #    variables:
                  #        CICD_RUNNER_THIRDPARTY_PATH: "/opt/depends/thirdparty"
                  #        CICD_RUNNER_TAG: "macos"
                  #    tags:
                  #        - macos
                  #    script:
                  #        - bash tools/run_py3_ut.sh
                  #    after_script:
                  #        - cd onebox && sh stop_all.sh
                  #    artifacts:
                  #        reports:
                  #            junit:
                  #                - python/test/*.xml
                  #
                  
micro_benchmark:
    stage: deploy
    script:
#        - tar xf bm_cases.tar.gz
        - bash tools/micro_bench.sh | tee micro_bench_report.txt
        - bash tools/gen_micro_bench_compare.sh
    dependencies:
        - build_fesql_on_linux
    artifacts:
        paths:
            - ./micro_bench_report.txt
            - ./benchmark_compare.html
        ## expose_as: "micro_benchmark"

deploy_jar:
    stage: deploy
    script:
        - bash tools/cicd/extract_intermediate_java_cicd_artifacts.sh linux
        # - bash tools/cicd/extract_intermediate_java_cicd_artifacts.sh mac
        - bash tools/cicd/deploy_fesql_spark_jar.sh
    dependencies:
        - build_fesql_on_linux
        - build_fesql_on_mac
    artifacts:
        paths:
            - ./java/fesql-spark/target/*.jar


