image: develop-registry.4pd.io/centos6_gcc7_build_env:0.1.0
variables:
    GIT_SUBMODULE_STRATEGY: normal
    CICD_RUNNER_THIRDPARTY_PATH: "/depends/thirdparty"

before_script:
    - source tools/init_env.profile.sh

stages:
    - build
    - test
    - benchmark

style_check:
    stage: build
    script:
        - bash tools/style_check.sh
    artifacts:
        reports:
            junit:
                - ./style.xml

build_py3sdk_and_case:
    stage: build
    script:
        - bash tools/run_py3_ut.sh
    artifacts:
        reports:
            junit:
                - python/test/*.xml

build_fesql_and_case:
    stage: build
    script:
        - bash tools/compile.sh
        - cd build && make coverage
    artifacts:
        reports:
            junit:
                - build/*.xml
        paths: 
            - "build/coverage"

build_fesql_and_case_on_mac:
    stage: build
    variables:
        CICD_RUNNER_THIRDPARTY_PATH: "/opt/depends/thirdparty"
        CICD_RUNNER_TAG: "macos"
    script:
        - bash tools/compile_and_test.sh
    tags:
        - macos

test_java_sdk:
    stage: test
    script:
        - bash tools/test_java_sdk.sh

test_java_sdk_on_mac:
    stage: test
    variables:
        CICD_RUNNER_THIRDPARTY_PATH: "/opt/depends/thirdparty"
        CICD_RUNNER_TAG: "macos"
    script:
        - bash tools/test_java_sdk.sh
    tags:
        - macos

micro_benchmark:
    stage: benchmark
    script:
        - bash tools/micro_bench.sh
