image: develop-registry.4pd.io/centos6_gcc7_rtidb_build:0.0.9
stages:
    - build
    - ut
#    - it-tablet
#    - it-ns
#    - deploy

build_rtidb:
    stage: build
    script:
        - ln -sf /usr/workdir/thirdparty thirdparty
        - ln -sf /usr/workdir/thirdsrc thirdsrc
        - source /root/.bashrc && bash steps/compile.sh
    artifacts:
        expire_in: 2h
        paths:
            - build/bin/rtidb

style_check:
    stage: build
    script:
        - source /root/.bashrc && bash tools/style_check.sh
    artifacts:
        reports:
            junit:
                - ./style.xml

#cpp_ut:
#    stage: ut
#    script:
#        - ln -sf /usr/workdir/thirdparty thirdparty
#        - ln -sf /usr/workdir/thirdsrc thirdsrc
#        - source /root/.bashrc && bash steps/compile.sh
#        - source /root/.bashrc && LD_LIBRARY_PATH=/usr/workdir/thirdparty/lib:$LD_LIBRARY_PATH bash steps/ut.sh
#    artifacts:
#        reports:
#            junit:
#                - reports/*.xml
#java_ut:
#    stage: ut
#    script:
#        - ln -sf /usr/workdir/thirdparty thirdparty
#        - ln -sf /usr/workdir/thirdsrc thirdsrc
#        - source /root/.bashrc && LD_LIBRARY_PATH=/usr/workdir/thirdparty/lib:$LD_LIBRARY_PATH bash steps/java_ut.sh
#    artifacts:
#        reports:
#            junit:
#                - java/target/surefire-reports/junitreports/TEST-*.xml
#                - java/target/surefire-reports/TEST-*.xml
#                - java/target/failsafe-reports/junitreports/TEST-*.xml
#                - java/target/failsafe-reports/TEST-*.xml
#
#tablet_one_demension:
#    stage: it-tablet
#    script:
#        - ln -sf /usr/workdir/thirdparty thirdparty
#        - ln -sf /usr/workdir/thirdsrc thirdsrc
#        - rm -rf ./test-output/integrationtest/test-reports/
#        - sed -i 's/log_level\ =\ debug/log_level\ =\ info/g' test-common/integrationtest/conf/test.conf
#        - source /root/.bashrc && LD_LIBRARY_PATH=/usr/workdir/thirdparty/lib:$LD_LIBRARY_PATH
#        - sh steps/integration_test.sh 0 "test" "ns_client"
#    artifacts:
#        reports:
#            junit:
#                - ./test-output/integrationtest/test-reports/*.xml
#
#tablet_multi_demension:
#    stage: it-tablet
#    script:
#        - ln -sf /usr/workdir/thirdparty thirdparty
#        - ln -sf /usr/workdir/thirdsrc thirdsrc
#        - rm -rf ./test-output/integrationtest/test-reports/
#        - sed -i 's/log_level\ =\ debug/log_level\ =\ info/g' test-common/integrationtest/conf/test.conf
#        - source /root/.bashrc && LD_LIBRARY_PATH=/usr/workdir/thirdparty/lib:$LD_LIBRARY_PATH
#        - sh steps/integration_test.sh 1 "test" "ns_client"
#    artifacts:
#        reports:
#            junit:
#                - ./test-output/integrationtest/test-reports/*.xml
#
#ns_one_demension:
#    stage: it-ns
#    script:
#        - ln -sf /usr/workdir/thirdparty thirdparty
#        - ln -sf /usr/workdir/thirdsrc thirdsrc
#        - rm -rf ./test-output/integrationtest/test-reports/
#        - sed -i 's/log_level\ =\ debug/log_level\ =\ info/g' test-common/integrationtest/conf/test.conf
#        - source /root/.bashrc && LD_LIBRARY_PATH=/usr/workdir/thirdparty/lib:$LD_LIBRARY_PATH
#        - bash steps/integration_test.sh 0 "ns_client" "disk"
#    artifacts:
#        reports:
#            junit:
#                - ./test-output/integrationtest/test-reports/*.xml
#
#ns_multi_demension:
#    stage: it-ns
#    script:
#        - ln -sf /usr/workdir/thirdparty thirdparty
#        - ln -sf /usr/workdir/thirdsrc thirdsrc
#        - rm -rf ./test-output/integrationtest/test-reports/
#        - sed -i 's/log_level\ =\ debug/log_level\ =\ info/g' test-common/integrationtest/conf/test.conf
#        - source /root/.bashrc && LD_LIBRARY_PATH=/usr/workdir/thirdparty/lib:$LD_LIBRARY_PATH
#        - bash steps/integration_test.sh 1 "ns_client" "disk"
#    artifacts:
#        reports:
#            junit:
#                - ./test-output/integrationtest/test-reports/*.xml
#
#disk_table:
#    stage: it-ns
#    script:
#        - ln -sf /usr/workdir/thirdparty thirdparty
#        - ln -sf /usr/workdir/thirdsrc thirdsrc
#        - rm -rf ./test-output/integrationtest/test-reports/
#        - sed -i 's/log_level\ =\ debug/log_level\ =\ info/g' test-common/integrationtest/conf/test.conf
#        - source /root/.bashrc && LD_LIBRARY_PATH=/usr/workdir/thirdparty/lib:$LD_LIBRARY_PATH
#        - bash steps/integration_test.sh 0 "disk"
#    artifacts:
#        reports:
#            junit:
#                - ./test-output/integrationtest/test-reports/*.xml

disktable-java:
    stage: ut
    script:
        - ln -sf /usr/workdir/thirdparty thirdparty
        - ln -sf /usr/workdir/thirdsrc thirdsrc
        - source /root/.bashrc && bash steps/auto_test.sh
    artifacts:
        reports:
            junit:
                - rtidb-auto-test/target/surefire-reports/junitreports/TEST-*.xml
                - rtidb-auto-test/target/surefire-reports/TEST-*.xml
                - rtidb-auto-test/target/failsafe-reports/junitreports/TEST-*.xml
                - rtidb-auto-test/target/failsafe-reports/TEST-*.xml
    after_script:
        - tar czvf $CI_COMMIT_SHA  auto-test-rtidb/target/allure-results
        - bash steps/upload-nexus.sh $CI_COMMIT_SHA
        - curl -s "http://auto.4paradigm.com/job/rtidb-test-report/buildWithParameters?token=gitlab&pkg=$CI_COMMIT_SHA&buildname=$CI_PIPELINE_ID"-"$CI_JOB_ID"
        - bash steps/get-report-url.sh rtidb-test-report $CI_PIPELINE_ID"-"$CI_JOB_ID


#deploy-package:
#    stage: deploy
#    script:
#        - ln -sf /usr/workdir/thirdparty thirdparty
#        - ln -sf /usr/workdir/thirdsrc thirdsrc
#        - source /root/.bashrc && bash steps/deploy_package.sh

