apiVersion: v1
kind: List
metadata: {}
items:
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    name: blobproxy
    namespace: {{index . "namespace"}}
    labels:
      rtidb: blobproxy
  spec:
    replicas: 1
    selector: 
      matchLabels:
        rtidb: blobproxy
    template:
      metadata:
        labels:
          rtidb: blobproxy
      spec:
        nodeSelector:
          prophet.4paradigm.com/system: "true"
        containers:
        - env:
          - name: zk_cluster
            value: {{.zk_cluster}}
          - name: zk_root_path
            value: "{{.zk_root_path}}"
          - name: blobproxy_port
            value: "8080"
          - name: ROLE
            value: blob_proxy
          - name: MY_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          image: {{.registry}}/{{.image}}
          name: rtidb
          imagePullPolicy: Always
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /status
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 60
          resources:
            limits:
              cpu: "1"
              memory: "512Mi"  
            requests:
              cpu: "1"
              memory: "512Mi"
        imagePullSecrets:
        - name: docker-secret
        securityContext: {}
- apiVersion: v1
  kind: Service
  metadata:
    name: blobproxy
    namespace: {{index . "namespace"}}
    labels:
      enable-on-api-gw: "true"
    annotations:
      api-gw-conf: '{"gw-api-confs": [{"listen-paths": "/rtidbblobproxy", "enable-auth": false, "stripe-url": false}]}'
  spec:
    ports:
    - name: blobproxy
      port: 80
      protocol: TCP
      targetPort: 8080
    selector:
      rtidb: blobproxy
    sessionAffinity: None
    type: ClusterIP
