name: FEDB-CICD
on: [pull_request]
env:
  GIT_SUBMODULE_STRATEGY: recursive
jobs:
  build:
    runs-on: self-hosted
    container:
      image: ghcr.io/4paradigm/centos6_gcc7_hybridsql:0.0.1
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.CR_PAT_ZW }}
    steps:
      - uses: actions/checkout@v1
      - name: update submodule
        run: |
           ln -s /opt/rh/sclo-git25/root/usr/bin/git /usr/local/bin/git
           git submodule update --init
      - name: build fesql
        run: source /root/.bashrc && bash tools/install_fesql.sh
      - name: build fedb
        run: |
          ln -s /opt/rh/sclo-git25/root/usr/bin/git /usr/local/bin/git
          ln -sf /depends/thirdparty thirdparty
          ln -sf /depends/thirdsrc thirdsrc
          source /root/.bashrc && bash steps/simple_compile.sh
          #     - uses: actions/upload-artifact@v1
          #        with:
          #          name: fedb
          #          path: build/bin/fedb
          #      - uses: actions/upload-artifact@v1
          #        with:
          #          name: \sql_sdk_test
          #          path: build/bin/sql_sdk_test
          #      - uses: actions/upload-artifact@v1
          #        with:
          #          name: sql_cluster_test
          #          path: build/bin/sql_cluster_tes
