name: FEDB-CICD
on: [pull_request]
env:
  GIT_SUBMODULE_STRATEGY: recursive
jobs:
  style_check:
    runs-on: self-hosted
    container:
      image: ghcr.io/4paradigm/centos6_gcc7_hybridsql:0.0.1
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.CR_PAT_ZW }}
    steps:
      - uses: actions/checkout@v1
      - name: style_check
        run: source /root/.bashrc && bash tools/style_check.sh
  build:
    needs: [style_check]
    runs-on: self-hosted
    container:
      image: ghcr.io/4paradigm/centos6_gcc7_hybridsql:0.0.1
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.CR_PAT_ZW }}
    steps:
      - uses: actions/checkout@v1
      - name: update submodule
        run: |
           git submodule update --init
      - name: build fesql
        run: source /root/.bashrc && bash tools/install_fesql.sh
      - name: build fedb
        run: |
          ln -sf /depends/thirdparty thirdparty
          ln -sf /depends/thirdsrc thirdsrc
          source /root/.bashrc && bash steps/simple_compile.sh
          #     - uses: actions/upload-artifact@v1
          #        with:
          #          name: fedb
          #          path: build/bin/fedb
          #      - uses: actions/upload-artifact@v1
          #        with:
          #          name: \sql_sdk_test
          #          path: build/bin/sql_sdk_test
          #      - uses: actions/upload-artifact@v1
          #        with:
          #          name: sql_cluster_test
          #          path: build/bin/sql_cluster_test
          #      - uses: actions/upload-artifact@v1
          #        with:
          #          name: libsql_jsdk.so
          #          path: build/src/sdk/libsql_jsdk.so
          #      - uses: actions/upload-artifact@v1
          #        with:
          #          name: sql_pysdk
          #          path: build/sql_pysdk/dist/
          #      - uses: actions/upload-artifact@v1
          #        with:
          #          name: python-whl
          #          path: build/python/dist/
