name: FEDB-CICD
on: [push, pull_request]
env:
  GIT_SUBMODULE_STRATEGY: recursive
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ls -al
  style_check:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/4paradigm/centos6_gcc7_fesql:legacy
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.CR_PAT_ZW }}
    steps:
      - name: git_enable
        run: source /opt/rh/sclo-git25/enable
      - uses: actions/checkout@v2
        with:
          submodules: true
      -
        run: |
          ls -al
          source /root/.bashrc && bash tools/style_check.sh
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/4paradigm/centos6_gcc7_fesql:legacy
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.CR_PAT_ZW }}
    steps:
      - name: git_enable
        run: cat '[ -r /opt/rh/sclo-git25/enable ] && . /opt/rh/sclo-git25/enable' > /etc/profile.d/enable-git.sh
      - uses: actions/checkout@v2
        with:
          submodules: true
      -
        run: |
          source /root/.bashrc && sh tools/install_fesql.sh
          ln -sf /depends/thirdparty thirdparty
          ln -sf /depends/thirdsrc thirdsrc
          source /root/.bashrc && bash steps/simple_compile.sh
      - uses: actions/upload-artifact@v2
        with:
          name: build-artifact
          path: |
            build/bin/rtidb
            build/bin/sql_sdk_test
            build/bin/sql_cluster_test
            build/bin/tablet_engine_test
            build/src/sdk/libsql_jsdk.so
            build/sql_pysdk/dist/*.whl
            build/python/dist/*.whl
          retention-days: 1