name: FEDB-CICD
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-16.04
    uses: 4paradigm/HybridSErelease@opensource_1.0.0.0
    steps:
      -
        run: |
          echo "test"
          ls -al
          pwd