name: FEDB-Dailybuild
on:
  schedule:
    - cron: '*/5 * * * *'
env:
  GIT_SUBMODULE_STRATEGY: recursive
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/4paradigm/centos6_gcc7_fesql:0.0.1-legacy
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.CR_PAT_ZW }}
    steps:
      - uses: actions/checkout@v1
        with:
          ref: 'main'
#          submodules: true
      - name: update nss
        run: yum update -y nss curl libcurl
      - name: update submodule
        run: |
          ln -s /opt/rh/sclo-git25/root/usr/bin/git /usr/local/bin/git
          git submodule init
          git submodule update
          cd fesql
          git checkout main
          git pull
          cd ..
#      - name: tar thirdparty
#        run: |
#           tar -zxvf /depends/thirdparty.tar.gz -C /depends/
#           mv /depends/depends/thirdparty /depends/
      - name: build fesql
        run: source /root/.bashrc && bash tools/install_fesql.sh
      - name: build fedb
        run: |
          ln -sf /depends/thirdparty thirdparty
          ln -sf /depends/thirdsrc thirdsrc
          source /root/.bashrc && bash steps/simple_compile.sh
      - run: |
          ls -al build
          ls -al build/bin
          ls -al build/src/sdk/
          ls -al build/sql_pysdk/
          ls -al build/python/dist/
      - uses: actions/upload-artifact@v1
        with:
          name: build-artifact
          path: |
            build/bin
            build/src/sdk
            build/sql_pysdk/dist
            build/python/dist
#  c++_ut:
#
#
#
#
#
#
#
#
#
#
#
#c++_ut:
#  stage: quick
#  script:
#    - ln -sf /depends/thirdparty thirdparty
#    - ln -sf /depends/thirdsrc thirdsrc
#    - source /root/.bashrc && sh tools/install_fesql.sh
#    - source /root/.bashrc && cd build && cmake -DSQL_PYSDK_ENABLE=OFF -DSQL_JAVASDK_ENABLE=OFF .. && make -j5 && cd ../
#    - source /root/.bashrc && LD_LIBRARY_PATH=/depends/thirdparty/lib:$LD_LIBRARY_PATH bash steps/ut.sh
#  artifacts:
#    reports:
#      junit:
#        - reports/*.xml
#  dependencies:
#    - build
#  except:
#    variables:
#      - $ENV_BUILD == "daily"