name: HybridSE CI

on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/4paradigm/centos6_gcc7_fesql:0.0.1-legacy
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.HYBRIDSE_PAT }}

    steps:
    - uses: actions/checkout@v1

    - name: Build
      shell: bash
      run: |
        ./tools/init_env.profile.sh
        ./tools/compile_and_test.sh
